all:
	gcc main.c LMC.c -o lmcProgram

program1:
	./lmcProgram program1.txt

program2:
	./lmcProgram program2.txt

program3:
	./lmcProgram program3.txt

program4:
	./lmcProgram program4.txt

program5:
	./lmcProgram program5.txt

program6:
	./lmcProgram program6.txt

program7:
	./lmcProgram program7.txt